server:
  error:
    whitelabel:
      enabled: false

error:
  path: /error

spring:
  mvc:
    static-path-pattern: /static/**
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: bcf283702c88974c445ca041bb3d6ad6
            client-secret: Mjlzvv3JOqrjnJ3IVkWsqDDNNlddmPuO
            redirect-uri: http://localhost:8080/JumpExpo/kakaologin
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
          provider:
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          type: trace
  thymeleaf:
    prefix: classpath:templates/thymeleaf/
    check_template-location: true
    suffix: .html
    mode: HTML
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://yeil03.iptime.org:3306/team1_2?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: team1
    password: 1234
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
    encoding:
      force-response: true

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE






